apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  volumeName: my-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests: 
      storage: 512Mi