apiVersion: v1
kind: Pod 
metadata: 
   name: busybox-ready
spec: 
 containers: 
   - name: busy 
     image: nginx 
     readinessProbe: 
        periodSeconds: 10 
        exec: 
          command: 
            - cat 
            - /tmp/nothing 
     resources: {}         