apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
    namespace: backup
    labels: 
      role: frontend
      env: demo 
spec:
  replicas: 2
  selector:
    matchLabels:
         role: frontend
  template:
     metadata: 
        labels:
          role: frontend
     spec:
        containers:
         - name: frontend
           image: nginx
           ports:
            - containerPort: 80