apiVersion: v1
kind: Pod
metadata:
  name: backend1
spec:
  containers:
  - name: app
    image: malyadr/vote1:v1
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "300m"